name: algoneer-website
blog-path: blog
url: http://localhost:8000
# we add .html to the links (to be able to serve them with a dev server)
theme-path: src/themes/algoneer 
articles-per-page: 5
path: /
languages:
  #these pages will be copied to all languages
  $all:
    pages:
      - src: common/404.html
        hidden: true
        footer: false
        attrs:
          sitemap: false
        title: 404
        slug: '404'
        name: '404'
  #english pages
  en:
    $include: site-en.yml
  #german pages
  de:
    $include: site-de.yml
translations:
  $include: translations/index.yml
context:
  env: development
